wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715249531.252551
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 23
      4: 3.9.19
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
n_rounds:
  desc: null
  value: 50
n_users:
  desc: null
  value: 10
n_epochs:
  desc: null
  value: 2
avg_method:
  desc: null
  value: Equal
model:
  desc: null
  value: mcmahan2NN
opt:
  desc: null
  value: sgd
pre_trained:
  desc: null
  value: false
lr:
  desc: null
  value: 0.075
batch_size:
  desc: null
  value: 32
lr_decay:
  desc: null
  value: 0.99
lr_decay_round:
  desc: null
  value: 5
dataset:
  desc: null
  value: mnist
split:
  desc: null
  value: iid
alpha:
  desc: null
  value: 0.1
gpu_id:
  desc: null
  value: null
eval_round:
  desc: null
  value: 1
debug:
  desc: null
  value: false
wandb:
  desc: null
  value: true
wandb_id:
  desc: null
  value: create0327
wandb_api:
  desc: null
  value: b2f21ce10a4365a21cfce06ad41f9a7f23d34639
exp_name:
  desc: null
  value: mcmahan2NN_lr0.075_iid_u10_epoch2
group_name:
  desc: null
  value: Gang_Test
