wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716279683.460282
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.19
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
