wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716291901.203459
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
n_rounds:
  desc: null
  value: 1000
n_users:
  desc: null
  value: 10
n_epochs:
  desc: null
  value: 1
avg_method:
  desc: null
  value: Equal
model:
  desc: null
  value: mcmahanCNN
opt:
  desc: null
  value: sgd
pre_trained:
  desc: null
  value: false
lr:
  desc: null
  value: 0.075
batch_size:
  desc: null
  value: 1024
lr_decay:
  desc: null
  value: 0.99
lr_decay_round:
  desc: null
  value: 5
dataset:
  desc: null
  value: cifar10
split:
  desc: null
  value: diri
alpha:
  desc: null
  value: 0.5
basic_fl:
  desc: null
  value: false
gpu_id:
  desc: null
  value: 1
eval_round:
  desc: null
  value: 10
debug:
  desc: null
  value: false
wandb:
  desc: null
  value: true
wandb_id:
  desc: null
  value: create0327
wandb_api:
  desc: null
  value: b2f21ce10a4365a21cfce06ad41f9a7f23d34639
exp_name:
  desc: null
  value: mcmahanCNN_fl_lr0.05_diri_a0.5_u10_b1024
group_name:
  desc: null
  value: LeNet_Test
